# Generated by Django 3.1.7 on 2021-02-22 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('dt_filed', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=150)),
                ('ticket_status', models.CharField(choices=[('NW', 'New'), ('DN', 'Done'), ('IP', 'In_Prograss'), ('IN', 'Invalid')], default='NW', max_length=2)),
                ('filed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
