# Generated by Django 3.1.7 on 2021-02-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0004_customuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='ticketitem',
            name='description',
            field=models.TextField(max_length=350),
        ),
    ]
